# 11-1 City, Country

# Write a function that accepts two parameters - city, country. 
# It should return a single string in the form of, for example:
# Santiago, Chile
# Store it in a module called city_function.py. 
# Create a unittest here for it. 
import unittest
from city_function import city_country

class TestCityCountry(unittest.TestCase):
    """Tests if output generated by city_country() is correct."""
    
    def test_city_country(self):
        "Is the string from output formatted correctly?"
        tested_string = city_country('Barcelona', 'Spain')
        self.assertEqual(tested_string, 'Barcelona, Spain')

if __name__ == '__main__':
    unittest.main()